### ISSUE TITLE
Documentation Error

### ISSUE THREAD

**Issue by billjuv** [thewestlabs/RNG-SyNC-doc#1]
Looks like a lot of effort went into this project, but not quite what I’m looking for at this time. I’m thinking, I’d rather try to capture the Bluetooth information coming from the BT-1 module I already have but it is nice to know your product is out there.

Not to be critical, but I do see one glaring error in your documentation. “MQQT” is incorrect. The proper acronym is “MQTT” (stands for Message Queuing Telemetry Transport). At first, I thought it was just a typo, but it caught my eye throughout your documentation… including on the BLE set up screen. Since this is a major feature of your project, I suggest you correct it. Just sayin’…

**Comment by thewestlabs** [comment]
Argh.. Thanks for reporting, that was a big mistake. Looks like I'll be stuck with the config variables in older devices.

BTW, if you already have bt-1 device and looking to directly read from it, I suggest you use any of these libraries:
https://github.com/cyrils/renogy-bt1
https://github.com/Olen/solar-monitor

**Comment by billjuv** [comment]
It was a pretty good size mistake, but totally understandable… MPPT, MQTT, MQQT (still jumps right out at me 😆). I see you’ve been busy though. The only “typo“ I still see is on the screenshot for the BLE app.

I’ve been checking out those BT-1 libraries you’ve mentioned but my son-in-law‘s solar greenhouse is a long way from the raspberry pi I put in his house (iffy for Bluetooth). I was actually hoping to find a way to convert BLE to WiFi then send to the RPi/MQTT solution like I used for a bunch of Bluetooth thermometers (https://github.com/tony-fav/tasmota-blerry), but I’m finding nothing and I’m not the point where I can figure that one out on my own.

I’ll probably just end up buying your unit since the greenhouse has strong Wi-Fi. I especially like that you include the micropython code and have the 3-D printable files available for a box. It’s a nice looking product.

Regards,
Bill J


On Jan 18, 2023, at 4:31 PM, thewestlabs ***@***.***> wrote:

﻿

Argh.. Thanks for reporting, that was a big mistake. Looks like I'll be stuck with the config variables in older devices.

BTW, if you already have bt-1 device and looking to directly read from it, I suggest you use any of these libraries:
https://github.com/cyrils/renogy-bt1
https://github.com/Olen/solar-monitor
