### ISSUE TITLE
Battery temp sensor missing

### ISSUE THREAD

**Issue by ajdezigns** [thewestlabs/RNG-SyNC-doc#2]
Hey The West Labs just got my unit and installed it but I did notice the battery temp sensor isn’t a sensor this tool seems to show when the Bluetooth unit did I had hoped to use this verbal to automate with is this something that can be added? Is there something you would need from me log wise to be able to implement it?

**Comment by thewestlabs** [comment]
Hello, can you contact me in the store page with your order number? I can send you instruction to update the firmware. Sorry I do not check this page often.
